### Nome: Wanderson Hermirio dos Santos
### Matricula: 201721210024

#### 1. Como importar pandas e verificar a versão?

In [1]:
import pandas as pd
pd.__version__

'0.24.2'

#### 2. Qual a diferença entre uma lista, um dicionário, um array numpy e uma series pandas?

##### Lista
na lista o operador *in* usa algoritmos diferentes para listas. Para listas, ele procura os elementos da lista em ordem.
##### Dicionario
Para dicionários, o Python usa um algoritmo chamado hashtable (tabela de dispersão), que tem uma propriedade notável: o operador in leva praticamente o mesmo tempo na busca, não importa quantos itens estejam no dicionário

##### Serie
Um serie e um array de uma dimensão, ou pode consederar tambem um coluno da tabela.

##### Array
Um Array e uma matriz de Valores de um mesmo tipo

#### 3. Crie uma série de pandas de cada um dos itens abaixo: uma lista, numpy e um dicionário

In [2]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [3]:
mylistSerie = pd.Series(mylist)
myarrSerie = pd.Series(myarr)
mydictSerie = pd.Series(mydict)

In [4]:
mylistSerie

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [5]:
myarrSerie

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

In [6]:
mydictSerie

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

#### 4 Como mudar os valores de uma série após ela ser criada?

In [7]:
mydictSerie.a = 123
mydictSerie

a    123
b      1
c      2
e      3
d      4
f      5
g      6
h      7
i      8
j      9
k     10
l     11
m     12
n     13
o     14
p     15
q     16
r     17
s     18
t     19
u     20
v     21
w     22
x     23
y     24
z     25
dtype: int64

#### 5 Combine ser1 e ser2 para formar um dataframe.

In [8]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [9]:
df = pd.DataFrame(ser1,ser2)
df

    0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

#### 6. Como atribuir nome ao índice da série? Dê um nome para a série que está chamando de ’alfabeto’.

In [10]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.rename('alfabeto')

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: alfabeto, dtype: object

#### 7. Como obter os itens da série A não presentes na série B?

In [11]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser3 = ser1.loc[~ser1.isin(ser2)]
ser3

0    1
1    2
2    3
dtype: int64

####  8. Reformule o ser da série em um dataframe com 7 linhas e 5 colunas.

In [12]:
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame([ser[0:5].tolist(), 
             ser[5:10].tolist(),
             ser[10:15].tolist(),
             ser[15:20].tolist(),
             ser[20:25].tolist(),
             ser[25:30].tolist(),
             ser[30:35].tolist()], 
             index=np.arange(7), 
             columns=np.arange(5))
df

   0  1  2  3  4
0  5  5  3  8  7
1  1  3  1  6  8
2  6  6  9  4  3
3  5  5  9  3  7
4  2  8  5  9  4
5  5  4  4  1  4
6  7  9  4  7  6

#### 9. De ser , extraia os itens nas posições na lista pos.

In [13]:
ser = pd.Series(list( ' abcdefghijklmnopqrstuvwxyz ' ))
pos = [0, 4, 8, 14, 20]
df = pd.DataFrame(ser,pos)
df

    0
0
4   d
8   h
14  n
20  t

#### 10. Concatene ser1 e ser2 vertical e horizontalmente (para formar um dataframe).

In [14]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df = pd.concat([ser1,ser2], axis=1)
df

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

#### 11. Importe as colunas ’crim’ e ’medv’ do conjunto de dados do BostonHousing como um dataframe.

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df[['crim', 'medv']]

         crim  medv
0     0.00632  24.0
1     0.02731  21.6
2     0.02729  34.7
3     0.03237  33.4
4     0.06905  36.2
5     0.02985  28.7
6     0.08829  22.9
7     0.14455  27.1
8     0.21124  16.5
9     0.17004  18.9
10    0.22489  15.0
11    0.11747  18.9
12    0.09378  21.7
13    0.62976  20.4
14    0.63796  18.2
15    0.62739  19.9
16    1.05393  23.1
17    0.78420  17.5
18    0.80271  20.2
19    0.72580  18.2
20    1.25179  13.6
21    0.85204  19.6
22    1.23247  15.2
23    0.98843  14.5
24    0.75026  15.6
25    0.84054  13.9
26    0.67191  16.6
27    0.95577  14.8
28    0.77299  18.4
29    1.00245  21.0
..        ...   ...
476   4.87141  16.7
477  15.02340  12.0
478  10.23300  14.6
479  14.33370  21.4
480   5.82401  23.0
481   5.70818  23.7
482   5.73116  25.0
483   2.81838  21.8
484   2.37857  20.6
485   3.67367  21.2
486   5.69175  19.1
487   4.83567  20.6
488   0.15086  15.2
489   0.18337   7.0
490   0.20746   8.1
491   0.10574  13.6
492   0.11132  20.1
493   0.17331  21.8
494   0.27957  24.5
495   0.17899  23.1
496   0.28960  19.7
497   0.26838  18.3
498   0.23912  21.2
499   0.17783  17.5
500   0.22438  16.8
501   0.06263  22.4
502   0.04527  20.6
503   0.06076  23.9
504   0.10959  22.0
505   0.04741  11.9

[506 rows x 2 columns]

#### 12. Renomeie a coluna Type como CarType em df e substitua o ’.’ nos nomes da colunas com ’_’.

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df = df.rename(columns={'Type': 'CarType'})
df

,Manufacturer,Model,CarType,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,None,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i
5,Buick,Century,Midsize,14.2,15.7,17.3,22.0,31.0,Driver only,NaN,...,6.0,189.0,105.0,69.0,41.0,28.0,16.0,NaN,USA,Buick Century
6,Buick,LeSabre,Large,19.9,20.8,NaN,19.0,28.0,Driver only,Front,...,6.0,200.0,111.0,74.0,42.0,30.5,17.0,3470.0,USA,Buick LeSabre
7,Buick,Roadmaster,Large,22.6,23.7,24.9,16.0,25.0,Driver only,Rear,...,6.0,216.0,116.0,78.0,45.0,30.5,21.0,4105.0,USA,Buick Roadmaster
8,Buick,Riviera,Midsize,26.3,26.3,26.3,19.0,27.0,Driver only,Front,...,5.0,198.0,108.0,NaN,41.0,26.5,14.0,3495.0,USA,Buick Riviera
9,Cadillac,DeVille,Large,33.0,34.7,36.3,16.0,25.0,Driver only,Front,...,6.0,206.0,114.0,73.0,43.0,35.0,18.0,3620.0,USA,Cadillac DeVille
10,Cadillac,Seville,Midsize,37.5,40.1,42.7,16.0,25.0,Driver & Passenger,Front,...,5.0,204.0,111.0,74.0,44.0,31.0,NaN,3935.0,USA,Cadillac Seville
11,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25.0,36.0,NaN,NaN,...,5.0,182.0,101.0,66.0,38.0,25.0,13.0,2490.0,USA,Chevrolet Cavalier
12,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25.0,34.0,Driver only,Front,...,5.0,184.0,103.0,68.0,39.0,26.0,NaN,2785.0,USA,Chevrolet Corsica
13,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19.0,28.0,Driver & Passenger,Rear,...,4.0,193.0,101.0,74.0,43.0,25.0,13.0,3240.0,USA,Chevrolet Camaro
14,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,NaN,29.0,None,Front,...,6.0,NaN,108.0,71.0,NaN,28.5,16.0,3195.0,USA,Chevrolet Lumina
15,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18.0,23.0,None,Front,...,7.0,178.0,110.0,74.0,44.0,30.5,NaN,3715.0,USA,Chevrolet Lumina_APV
16,Chevrolet,Astro,Van,14.7,16.6,18.6,15.0,20.0,None,4WD,...,8.0,194.0,111.0,78.0,42.0,33.5,NaN,4025.0,USA,Chevrolet Astro
17,Chevrolet,Caprice,Large,18.0,18.8,19.6,17.0,26.0,Driver only,Rear,...,6.0,214.0,116.0,77.0,42.0,29.5,20.0,3910.0,USA,Chevrolet Caprice
18,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17.0,25.0,Driver only,Rear,...,2.0,179.0,96.0,74.0,43.0,NaN,NaN,3380.0,NaN,Chevrolet Corvette
19,NaN,Concorde,Large,18.4,18.4,18.4,20.0,28.0,Driver & Passenger,Front,...,6.0,203.0,113.0,74.0,NaN,31.0,15.0,3515.0,USA,Chrylser Concorde
20,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23.0,28.0,Driver & Passenger,Front,...,6.0,183.0,104.0,68.0,41.0,30.5,14.0,3085.0,USA,Chrysler LeBaron
21,Chrysler,Imperial,Large,29.5,29.5,29.5,20.0,26.0,Driver only,Front,...,6.0,203.0,110.0,69.0,44.0,36.0,17.0,3570.0,USA,Chrysler Imperial
22,Dodge,Colt,Small,7.9,9.2,10.6,29.0,33.0,None,Front,...,5.0,174.0,98.0,66.0,32.0,NaN,11.0,2270.0,USA,Dodge Colt
23,Dodge,Shadow,Small,8.4,11.3,14.2,23.0,29.0,Driver only,Front,...,5.0,172.0,97.0,67.0,38.0,26.5,NaN,2670.0,USA,Dodge Shadow
24,Dodge,Spirit,Compact,11.9,13.3,14.7,22.0,27.0,Driver only,Front,...,6.0,181.0,104.0,68.0,39.0,30.5,NaN,2970.0,USA,Dodge Spirit
25,Dodge,Caravan,Van,NaN,19.0,24.4,17.0,21.0,Driver only,4WD,...,7.0,175.0,112.0,72.0,42.0,26.5,NaN,3705.0,USA,Dodge Caravan
26,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21.0,NaN,Driver only,Front,...,6.0,192.0,105.0,69.0,42.0,30.5,16.0,3080.0,USA,Dodge Dynasty
27,Dodge,Stealth,Sporty,18.5,25.8,33.1,NaN,24.0,Driver only,4WD,...,4.0,180.0,97.0,NaN,40.0,20.0,11.0,3805.0,USA,Dodge Stealth
28,Eagle,Summit,Small,7.9,12.2,16.5,29.0,33.0,None,Front,...,5.0,174.0,98.0,66.0,36.0,26.5,11.0,2295.0,USA,Eagle Summit
29,Eagle,Vision,Large,NaN,19.3,21.2,20.0,28.0,Driver & Passenger,Front,...,6.0,202.0,113.0,74.0,40.0,30.0,15.0,3490.0,USA,Eagle Vision
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Nissan,Sentra,Small,8.7,11.8,14.9,29.0,33.0,Driver only,Front,...,5.0,170.0,96.0,66.0,33.0,26.0,NaN,NaN,non-USA,Nissan Sentra
64,Nissan,Altima,Compact,13.0,15.7,18.3,24.0,30.0,Driver only,Front,...,5.0,181.0,103.0,67.0,40.0,28.5,14.0,3050.0,non-USA,Nissan Altima
65,Nissan,Quest,Van,16.7,19.1,21.5,17.0,23.0,None,Front,...,7.0,190.0,112.0,74.0,41.0,27.0,NaN,4100.0,non-USA,Nissan Quest
66,Nissan,Maxima,Midsize,21.0,21.5,22.0,21.0,26.0,Driver only,Front,...,5.0,188.0,104.0,69.0,41.0,28.5,14.0,3200.0,non-USA,Nissan Maxima
67,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24.0,31.0,None,Front,...,5.0,188.0,103.0,67.0,39.0,28.0,14.0,2910.0,USA,Oldsmobile Achieva
68,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23.0,31.0,Driver only,Front,...,5.0,190.0,105.0,70.0,42.0,28.0,16.0,2890.0,USA,Oldsmobile Cutlass_Ciera
69,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18.0,23.0,None,Front,...,7.0,NaN,110.0,74.0,44.0,30.5,NaN,3715.0,USA,Oldsmobile Silhouette
70,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,NaN,28.0,Driver only,Front,...,6.0,201.0,111.0,74.0,42.0,31.5,17.0,3470.0,USA,Oldsmobile Eighty-Eight
71,Plymouth,Laser,Sporty,11.4,14.4,17.4,NaN,30.0,None,4WD,...,4.0,173.0,97.0,67.0,39.0,24.5,8.0,2640.0,NaN,Plymouth Laser
72,Pontiac,LeMans,Small,NaN,9.0,9.9,31.0,41.0,None,Front,...,4.0,177.0,99.0,66.0,35.0,25.5,17.0,2350.0,USA,Pontiac LeMans
73,Pontiac,Sunbird,Compact,9.4,11.1,12.8,NaN,31.0,None,NaN,...,5.0,181.0,101.0,66.0,39.0,25.0,13.0,NaN,USA,NaN
74,Pontiac,Firebird,NaN,14.0,17.7,21.4,19.0,28.0,Driver & Passenger,Rear,...,4.0,196.0,101.0,75.0,43.0,25.0,13.0,3240.0,USA,Pontiac Firebird
75,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19.0,27.0,None,Front,...,5.0,195.0,108.0,72.0,41.0,28.5,16.0,3450.0,USA,Pontiac Grand_Prix
76,Pontiac,Bonneville,Large,19.4,24.4,29.4,19.0,28.0,Driver & Passenger,Front,...,6.0,177.0,111.0,74.0,43.0,30.5,18.0,3495.0,USA,Pontiac Bonneville
77,Saab,900,Compact,20.3,28.7,37.1,20.0,26.0,NaN,Front,...,5.0,NaN,99.0,67.0,37.0,26.5,14.0,2775.0,non-USA,Saab 900
78,Saturn,SL,Small,9.2,NaN,12.9,NaN,38.0,Driver only,Front,...,5.0,176.0,102.0,68.0,40.0,26.5,NaN,2495.0,USA,Saturn SL
79,Subaru,Justy,Small,7.3,8.4,9.5,33.0,37.0,None,4WD,...,4.0,146.0,90.0,60.0,32.0,23.5,10.0,2045.0,non-USA,Subaru Justy
80,Subaru,Loyale,Small,10.5,10.9,11.3,25.0,30.0,None,4WD,...,5.0,175.0,97.0,65.0,35.0,27.5,15.0,2490.0,non-USA,Subaru Loyale
81,Subaru,Legacy,Compact,16.3,19.5,22.7,23.0,30.0,Driver only,4WD,...,5.0,179.0,102.0,67.0,37.0,27.0,14.0,3085.0,non-USA,Subaru Legacy
82,Suzuki,Swift,NaN,7.3,8.6,NaN,39.0,43.0,None,Front,...,4.0,161.0,93.0,NaN,34.0,27.5,10.0,1965.0,non-USA,Suzuki Swift
83,Toyota,Tercel,Small,NaN,9.8,11.8,32.0,37.0,Driver only,Front,...,NaN,162.0,94.0,NaN,36.0,24.0,11.0,2055.0,non-USA,Toyota Tercel
84,Toyota,Celica,Sporty,14.2,18.4,22.6,25.0,32.0,NaN,Front,...,4.0,174.0,99.0,69.0,NaN,23.0,13.0,2950.0,non-USA,Toyota Celica
85,Toyota,Camry,Midsize,15.2,NaN,21.2,22.0,29.0,Driver only,NaN,...,5.0,188.0,103.0,70.0,38.0,28.5,15.0,3030.0,non-USA,Toyota Camry
86,Toyota,Previa,Van,NaN,22.7,26.6,18.0,22.0,Driver only,4WD,...,7.0,187.0,113.0,71.0,41.0,35.0,NaN,3785.0,non-USA,Toyota Previa
87,Volkswagen,Fox,Small,8.7,9.1,9.5,25.0,33.0,None,Front,...,4.0,163.0,93.0,63.0,34.0,26.0,10.0,2240.0,non-USA,Volkswagen Fox
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17.0,21.0,None,Front,...,7.0,187.0,115.0,72.0,38.0,34.0,NaN,3960.0,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21.0,30.0,None,Front,...,5.0,180.0,103.0,67.0,35.0,31.5,14.0,2985.0,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18.0,25.0,None,Front,...,4.0,159.0,97.0,66.0,36.0,26.0,15.0,2810.0,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.8,22.7,23.5,21.0,28.0,Driver only,Rear,...,5.0,190.0,104.0,67.0,37.0,29.5,14.0,2985.0,non-USA,Volvo 240
92,NaN,850,Midsize,24.8,26.7,28.5,20.0,28.0,Driver & Passenger,Front,...,5.0,184.0,105.0,69.0,38.0,30.0,15.0,3245.0,non-USA,Volvo 850

#### 13. Verifique se o dataframe tem algum valor ausente.

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.isnull().values.any()

True

#### 14. Conte o número de valores ausentes em cada coluna do df . Qual coluna tem o número máximo de valores ausentes?

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
len(df) - df.count().sort_values()

Luggage.room          19
MPG.city               9
Fuel.tank.capacity     8
Weight                 7
Min.Price              7
DriveTrain             7
Horsepower             7
AirBags                6
Width                  6
Rev.per.mile           6
Man.trans.avail        5
Max.Price              5
Turn.circle            5
Cylinders              5
Origin                 5
Manufacturer           4
Rear.seat.room         4
Length                 4
RPM                    3
Type                   3
Make                   3
EngineSize             2
MPG.highway            2
Price                  2
Passengers             2
Wheelbase              1
Model                  1
dtype: int64

#### 15. Obtenha a primeira coluna ’a’ em df como um dataframe (em vez de uma série).

In [31]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df[['a']]

    a
0   0
1   5
2  10
3  15

#### 16. Como alterar a ordem das colunas de um dataframe? Para isso, respondam as três questões:

#### (a) Em df, troque as colunas ’a’ e ’c’.

In [32]:
valorA = df['a'].copy()
df['a'] =  df['b']
df['b'] = valorA
df

    a   b   c   d   e
0   1   0   2   3   4
1   6   5   7   8   9
2  11  10  12  13  14
3  16  15  17  18  19

#### (b) Crie uma função genérica para trocar duas colunas, sem codificar os nomes das colunas.

In [34]:
def changeColumns( data, colA, colB ):
    valorA = data[colB].copy()
    data[colB] = data[colA]
    data[colA] = valorA

changeColumns( df, 'a', 'b')
df

    a   b   c   d   e
0   1   0   2   3   4
1   6   5   7   8   9
2  11  10  12  13  14
3  16  15  17  18  19

#### (c) Classifique as colunas em ordem alfabética inversa, ou seja, colume ’e’ primeiro até a coluna ’a’ last.

In [35]:
df.loc[:,::-1]

    e   d   c   b   a
0   4   3   2   0   1
1   9   8   7   5   6
2  14  13  12  10  11
3  19  18  17  15  16

#### 17. Altere as configurações de exibição de Pandas ao imprimir o dataframe df mostre no máximo 10 linhas e 10 colunas.

In [38]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.iloc[0:10, 0:10]

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,None,Front
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear
5,Buick,Century,Midsize,14.2,15.7,17.3,22.0,31.0,Driver only,NaN
6,Buick,LeSabre,Large,19.9,20.8,NaN,19.0,28.0,Driver only,Front
7,Buick,Roadmaster,Large,22.6,23.7,24.9,16.0,25.0,Driver only,Rear
8,Buick,Riviera,Midsize,26.3,26.3,26.3,19.0,27.0,Driver only,Front
9,Cadillac,DeVille,Large,33.0,34.7,36.3,16.0,25.0,Driver only,Front

#### 18. A partir de df , filtre o ’Manufacturer’, ’Model’ e ’Type’ para cada 20 linhas, começando em 1o (linha 0).

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df[['Manufacturer','Model', 'Type']]

   Manufacturer          Model     Type
0         Acura        Integra    Small
1           NaN         Legend  Midsize
2          Audi             90  Compact
3          Audi            100  Midsize
4           BMW           535i  Midsize
5         Buick        Century  Midsize
6         Buick        LeSabre    Large
7         Buick     Roadmaster    Large
8         Buick        Riviera  Midsize
9      Cadillac        DeVille    Large
10     Cadillac        Seville  Midsize
11    Chevrolet       Cavalier  Compact
12    Chevrolet        Corsica  Compact
13    Chevrolet         Camaro   Sporty
14    Chevrolet         Lumina  Midsize
15    Chevrolet     Lumina_APV      Van
16    Chevrolet          Astro      Van
17    Chevrolet        Caprice    Large
18    Chevrolet       Corvette   Sporty
19          NaN       Concorde    Large
20     Chrysler        LeBaron  Compact
21     Chrysler       Imperial    Large
22        Dodge           Colt    Small
23        Dodge         Shadow    Small
24        Dodge         Spirit  Compact
25        Dodge        Caravan      Van
26        Dodge        Dynasty  Midsize
27        Dodge        Stealth   Sporty
28        Eagle         Summit    Small
29        Eagle         Vision    Large
..          ...            ...      ...
63       Nissan         Sentra    Small
64       Nissan         Altima  Compact
65       Nissan          Quest      Van
66       Nissan         Maxima  Midsize
67   Oldsmobile        Achieva  Compact
68   Oldsmobile  Cutlass_Ciera  Midsize
69   Oldsmobile     Silhouette      Van
70   Oldsmobile   Eighty-Eight    Large
71     Plymouth          Laser   Sporty
72      Pontiac         LeMans    Small
73      Pontiac        Sunbird  Compact
74      Pontiac       Firebird      NaN
75      Pontiac     Grand_Prix  Midsize
76      Pontiac     Bonneville    Large
77         Saab            900  Compact
78       Saturn             SL    Small
79       Subaru          Justy    Small
80       Subaru         Loyale    Small
81       Subaru         Legacy  Compact
82       Suzuki          Swift      NaN
83       Toyota         Tercel    Small
84       Toyota         Celica   Sporty
85       Toyota          Camry  Midsize
86       Toyota         Previa      Van
87   Volkswagen            Fox    Small
88   Volkswagen        Eurovan      Van
89   Volkswagen         Passat  Compact
90   Volkswagen        Corrado   Sporty
91        Volvo            240  Compact
92          NaN            850  Midsize

[93 rows x 3 columns]

#### 9. Obtenha as duas últimas linhas de df cuja soma da linha é maior que 100.

In [42]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)

def test(df):
    lista = []
    
    for i in range(len(df)):
        if ( df.iloc[-i].sum() > 100 ):
            lista.append(df.iloc[-i])

            if len(lista) == 2: 
                return lista

lista = test(df)
print(f"\nindice {lista[0].name} : {lista[0].sum()}\nindice {lista[1].name} : {lista[1].sum()}")

     0   1   2   3
0   24  17  23  26
1   15  17  35  10
2   17  33  11  15
3   29  32  12  19
4   20  27  34  12
5   36  27  19  10
6   25  20  26  16
7   24  30  35  10
8   29  24  27  34
9   22  27  11  24
10  24  12  12  11
11  10  14  14  17
12  13  36  33  12
13  23  17  18  34
14  19  32  37  21

indice 14 : 109
indice 8 : 114

#### 20. Troque as linhas 1 e 2 em df.

In [43]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
line1 = df.iloc[1].copy()
df.iloc[1] = df.iloc[2]
df.iloc[2] = line1

df

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24